namespace CinemaManagement.UI.Forms
{
    partial class frmAdmin_QuanLyPhong
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges21 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges22 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges5 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges6 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges7 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges8 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges9 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges10 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges11 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges12 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges13 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges14 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges15 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges16 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges17 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges18 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges19 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges20 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges23 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges24 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges4 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges1 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges2 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            pnlLeft = new Guna.UI2.WinForms.Guna2Panel();
            btnLamMoi = new Guna.UI2.WinForms.Guna2Button();
            btnXoa = new Guna.UI2.WinForms.Guna2Button();
            btnSua = new Guna.UI2.WinForms.Guna2Button();
            btnThem = new Guna.UI2.WinForms.Guna2Button();
            cboTrangThai = new Guna.UI2.WinForms.Guna2ComboBox();
            label5 = new Label();
            cboLoaiPhong = new Guna.UI2.WinForms.Guna2ComboBox();
            label4 = new Label();
            txtSucChua = new Guna.UI2.WinForms.Guna2TextBox();
            label3 = new Label();
            txtTenPhong = new Guna.UI2.WinForms.Guna2TextBox();
            label2 = new Label();
            pnlRight = new Guna.UI2.WinForms.Guna2Panel();
            dgvPhong = new Guna.UI2.WinForms.Guna2DataGridView();
            cmsPhong = new Guna.UI2.WinForms.Guna2ContextMenuStrip();
            txtTimKiem = new Guna.UI2.WinForms.Guna2TextBox();
            btnTimKiem = new Guna.UI2.WinForms.Guna2Button();
            xóaToolStripMenuItem = new ToolStripMenuItem();
            sửaToolStripMenuItem = new ToolStripMenuItem();
            pnlLeft.SuspendLayout();
            pnlRight.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPhong).BeginInit();
            cmsPhong.SuspendLayout();
            SuspendLayout();
            // 
            // pnlLeft
            // 
            pnlLeft.BackColor = Color.Salmon;
            pnlLeft.Controls.Add(btnTimKiem);
            pnlLeft.Controls.Add(txtTimKiem);
            pnlLeft.Controls.Add(btnLamMoi);
            pnlLeft.Controls.Add(btnXoa);
            pnlLeft.Controls.Add(btnSua);
            pnlLeft.Controls.Add(btnThem);
            pnlLeft.Controls.Add(cboTrangThai);
            pnlLeft.Controls.Add(label5);
            pnlLeft.Controls.Add(cboLoaiPhong);
            pnlLeft.Controls.Add(label4);
            pnlLeft.Controls.Add(txtSucChua);
            pnlLeft.Controls.Add(label3);
            pnlLeft.Controls.Add(txtTenPhong);
            pnlLeft.Controls.Add(label2);
            pnlLeft.CustomizableEdges = customizableEdges21;
            pnlLeft.Dock = DockStyle.Left;
            pnlLeft.Location = new Point(0, 0);
            pnlLeft.Name = "pnlLeft";
            pnlLeft.ShadowDecoration.CustomizableEdges = customizableEdges22;
            pnlLeft.Size = new Size(350, 650);
            pnlLeft.TabIndex = 0;
            // 
            // btnLamMoi
            // 
            btnLamMoi.BorderRadius = 10;
            btnLamMoi.CustomizableEdges = customizableEdges5;
            btnLamMoi.FillColor = Color.Maroon;
            btnLamMoi.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnLamMoi.ForeColor = Color.White;
            btnLamMoi.Location = new Point(181, 580);
            btnLamMoi.Name = "btnLamMoi";
            btnLamMoi.ShadowDecoration.CustomizableEdges = customizableEdges6;
            btnLamMoi.Size = new Size(98, 45);
            btnLamMoi.TabIndex = 0;
            btnLamMoi.Text = "LÀM MỚI";
            btnLamMoi.Click += btnLamMoi_Click;
            // 
            // btnXoa
            // 
            btnXoa.BorderRadius = 10;
            btnXoa.CustomizableEdges = customizableEdges7;
            btnXoa.FillColor = Color.Maroon;
            btnXoa.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnXoa.ForeColor = Color.White;
            btnXoa.Location = new Point(61, 580);
            btnXoa.Name = "btnXoa";
            btnXoa.ShadowDecoration.CustomizableEdges = customizableEdges8;
            btnXoa.Size = new Size(105, 45);
            btnXoa.TabIndex = 1;
            btnXoa.Text = "XÓA";
            btnXoa.Click += btnXoa_Click;
            // 
            // btnSua
            // 
            btnSua.BorderRadius = 10;
            btnSua.CustomizableEdges = customizableEdges9;
            btnSua.FillColor = Color.Maroon;
            btnSua.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnSua.ForeColor = Color.White;
            btnSua.Location = new Point(181, 520);
            btnSua.Name = "btnSua";
            btnSua.ShadowDecoration.CustomizableEdges = customizableEdges10;
            btnSua.Size = new Size(98, 45);
            btnSua.TabIndex = 2;
            btnSua.Text = "SỬA";
            btnSua.Click += btnSua_Click;
            // 
            // btnThem
            // 
            btnThem.BorderRadius = 10;
            btnThem.CustomizableEdges = customizableEdges11;
            btnThem.FillColor = Color.Maroon;
            btnThem.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            btnThem.ForeColor = Color.White;
            btnThem.Location = new Point(61, 520);
            btnThem.Name = "btnThem";
            btnThem.ShadowDecoration.CustomizableEdges = customizableEdges12;
            btnThem.Size = new Size(105, 45);
            btnThem.TabIndex = 3;
            btnThem.Text = "THÊM";
            btnThem.Click += btnThem_Click;
            // 
            // cboTrangThai
            // 
            cboTrangThai.BackColor = Color.Transparent;
            cboTrangThai.BorderRadius = 10;
            cboTrangThai.CustomizableEdges = customizableEdges13;
            cboTrangThai.DrawMode = DrawMode.OwnerDrawFixed;
            cboTrangThai.DropDownStyle = ComboBoxStyle.DropDownList;
            cboTrangThai.FocusedColor = Color.Empty;
            cboTrangThai.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            cboTrangThai.ForeColor = Color.FromArgb(68, 88, 112);
            cboTrangThai.ItemHeight = 30;
            cboTrangThai.Items.AddRange(new object[] { "Hoạt động", "Bảo trì", "Tạm ngưng" });
            cboTrangThai.Location = new Point(26, 441);
            cboTrangThai.Name = "cboTrangThai";
            cboTrangThai.ShadowDecoration.CustomizableEdges = customizableEdges14;
            cboTrangThai.Size = new Size(300, 36);
            cboTrangThai.TabIndex = 8;
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            label5.ForeColor = SystemColors.ControlLightLight;
            label5.Location = new Point(26, 416);
            label5.Name = "label5";
            label5.Size = new Size(97, 23);
            label5.TabIndex = 9;
            label5.Text = "Trạng thái:";
            // 
            // cboLoaiPhong
            // 
            cboLoaiPhong.BackColor = Color.Transparent;
            cboLoaiPhong.BorderRadius = 10;
            cboLoaiPhong.CustomizableEdges = customizableEdges15;
            cboLoaiPhong.DrawMode = DrawMode.OwnerDrawFixed;
            cboLoaiPhong.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLoaiPhong.FocusedColor = Color.Empty;
            cboLoaiPhong.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            cboLoaiPhong.ForeColor = Color.FromArgb(68, 88, 112);
            cboLoaiPhong.ItemHeight = 30;
            cboLoaiPhong.Items.AddRange(new object[] { "2D Standard", "3D", "IMAX", "Sweetbox", "4DX" });
            cboLoaiPhong.Location = new Point(26, 361);
            cboLoaiPhong.Name = "cboLoaiPhong";
            cboLoaiPhong.ShadowDecoration.CustomizableEdges = customizableEdges16;
            cboLoaiPhong.Size = new Size(300, 36);
            cboLoaiPhong.TabIndex = 6;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            label4.ForeColor = SystemColors.ControlLightLight;
            label4.Location = new Point(26, 336);
            label4.Name = "label4";
            label4.Size = new Size(105, 23);
            label4.TabIndex = 10;
            label4.Text = "Loại phòng:";
            // 
            // txtSucChua
            // 
            txtSucChua.BorderRadius = 10;
            txtSucChua.CustomizableEdges = customizableEdges17;
            txtSucChua.DefaultText = "";
            txtSucChua.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            txtSucChua.Location = new Point(26, 281);
            txtSucChua.Margin = new Padding(3, 4, 3, 4);
            txtSucChua.Name = "txtSucChua";
            txtSucChua.PlaceholderText = "";
            txtSucChua.SelectedText = "";
            txtSucChua.ShadowDecoration.CustomizableEdges = customizableEdges18;
            txtSucChua.Size = new Size(300, 40);
            txtSucChua.TabIndex = 4;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            label3.ForeColor = SystemColors.ControlLightLight;
            label3.Location = new Point(26, 256);
            label3.Name = "label3";
            label3.Size = new Size(135, 23);
            label3.TabIndex = 11;
            label3.Text = "Sức chứa (Ghế):";
            // 
            // txtTenPhong
            // 
            txtTenPhong.BorderRadius = 10;
            txtTenPhong.CustomizableEdges = customizableEdges19;
            txtTenPhong.DefaultText = "";
            txtTenPhong.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            txtTenPhong.Location = new Point(26, 201);
            txtTenPhong.Margin = new Padding(3, 4, 3, 4);
            txtTenPhong.Name = "txtTenPhong";
            txtTenPhong.PlaceholderText = "";
            txtTenPhong.SelectedText = "";
            txtTenPhong.ShadowDecoration.CustomizableEdges = customizableEdges20;
            txtTenPhong.Size = new Size(300, 40);
            txtTenPhong.TabIndex = 2;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            label2.ForeColor = SystemColors.ControlLightLight;
            label2.Location = new Point(26, 176);
            label2.Name = "label2";
            label2.Size = new Size(99, 23);
            label2.TabIndex = 12;
            label2.Text = "Tên phòng:";
            // 
            // pnlRight
            // 
            pnlRight.BackColor = Color.Salmon;
            pnlRight.Controls.Add(dgvPhong);
            pnlRight.CustomizableEdges = customizableEdges23;
            pnlRight.Dock = DockStyle.Fill;
            pnlRight.Location = new Point(350, 0);
            pnlRight.Name = "pnlRight";
            pnlRight.Padding = new Padding(20);
            pnlRight.ShadowDecoration.CustomizableEdges = customizableEdges24;
            pnlRight.Size = new Size(946, 650);
            pnlRight.TabIndex = 0;
            // 
            // dgvPhong
            // 
            dataGridViewCellStyle1.BackColor = Color.White;
            dgvPhong.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.Maroon;
            dataGridViewCellStyle2.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dgvPhong.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvPhong.ColumnHeadersHeight = 40;
            dgvPhong.ContextMenuStrip = cmsPhong;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI", 9F);
            dataGridViewCellStyle3.ForeColor = Color.FromArgb(71, 69, 94);
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(231, 229, 255);
            dataGridViewCellStyle3.SelectionForeColor = Color.FromArgb(71, 69, 94);
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvPhong.DefaultCellStyle = dataGridViewCellStyle3;
            dgvPhong.Dock = DockStyle.Fill;
            dgvPhong.GridColor = Color.FromArgb(231, 229, 255);
            dgvPhong.Location = new Point(20, 20);
            dgvPhong.Name = "dgvPhong";
            dgvPhong.ReadOnly = true;
            dgvPhong.RowHeadersVisible = false;
            dgvPhong.RowHeadersWidth = 51;
            dgvPhong.RowTemplate.Height = 35;
            dgvPhong.Size = new Size(906, 610);
            dgvPhong.TabIndex = 0;
            dgvPhong.ThemeStyle.AlternatingRowsStyle.BackColor = Color.White;
            dgvPhong.ThemeStyle.AlternatingRowsStyle.Font = null;
            dgvPhong.ThemeStyle.AlternatingRowsStyle.ForeColor = Color.Empty;
            dgvPhong.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = Color.Empty;
            dgvPhong.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = Color.Empty;
            dgvPhong.ThemeStyle.BackColor = Color.White;
            dgvPhong.ThemeStyle.GridColor = Color.FromArgb(231, 229, 255);
            dgvPhong.ThemeStyle.HeaderStyle.BackColor = Color.Maroon;
            dgvPhong.ThemeStyle.HeaderStyle.BorderStyle = DataGridViewHeaderBorderStyle.None;
            dgvPhong.ThemeStyle.HeaderStyle.Font = new Font("Segoe UI", 9F);
            dgvPhong.ThemeStyle.HeaderStyle.ForeColor = Color.White;
            dgvPhong.ThemeStyle.HeaderStyle.HeaightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvPhong.ThemeStyle.HeaderStyle.Height = 40;
            dgvPhong.ThemeStyle.ReadOnly = true;
            dgvPhong.ThemeStyle.RowsStyle.BackColor = Color.White;
            dgvPhong.ThemeStyle.RowsStyle.BorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvPhong.ThemeStyle.RowsStyle.Font = new Font("Segoe UI", 9F);
            dgvPhong.ThemeStyle.RowsStyle.ForeColor = Color.FromArgb(71, 69, 94);
            dgvPhong.ThemeStyle.RowsStyle.Height = 35;
            dgvPhong.ThemeStyle.RowsStyle.SelectionBackColor = Color.FromArgb(231, 229, 255);
            dgvPhong.ThemeStyle.RowsStyle.SelectionForeColor = Color.FromArgb(71, 69, 94);
            dgvPhong.CellContentClick += dgvPhong_CellContentClick;
            // 
            // cmsPhong
            // 
            cmsPhong.ImageScalingSize = new Size(20, 20);
            cmsPhong.Items.AddRange(new ToolStripItem[] { xóaToolStripMenuItem, sửaToolStripMenuItem });
            cmsPhong.Name = "cmsPhong";
            cmsPhong.RenderStyle.ArrowColor = Color.FromArgb(151, 143, 255);
            cmsPhong.RenderStyle.BorderColor = Color.Gainsboro;
            cmsPhong.RenderStyle.ColorTable = null;
            cmsPhong.RenderStyle.RoundedEdges = true;
            cmsPhong.RenderStyle.SelectionArrowColor = Color.White;
            cmsPhong.RenderStyle.SelectionBackColor = Color.FromArgb(100, 88, 255);
            cmsPhong.RenderStyle.SelectionForeColor = Color.White;
            cmsPhong.RenderStyle.SeparatorColor = Color.Gainsboro;
            cmsPhong.RenderStyle.TextRenderingHint = System.Drawing.Text.TextRenderingHint.SystemDefault;
            cmsPhong.Size = new Size(211, 80);
            cmsPhong.Opening += cmsPhong_Opening;
            // 
            // txtTimKiem
            // 
            txtTimKiem.BorderRadius = 10;
            txtTimKiem.CustomizableEdges = customizableEdges3;
            txtTimKiem.DefaultText = "";
            txtTimKiem.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtTimKiem.Location = new Point(26, 20);
            txtTimKiem.Margin = new Padding(3, 4, 3, 4);
            txtTimKiem.Name = "txtTimKiem";
            txtTimKiem.PlaceholderText = "Nhập thông tin tìm kiếm";
            txtTimKiem.SelectedText = "";
            txtTimKiem.ShadowDecoration.CustomizableEdges = customizableEdges4;
            txtTimKiem.Size = new Size(300, 40);
            txtTimKiem.TabIndex = 13;
            // 
            // btnTimKiem
            // 
            btnTimKiem.BorderRadius = 10;
            btnTimKiem.CustomizableEdges = customizableEdges1;
            btnTimKiem.FillColor = Color.Maroon;
            btnTimKiem.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold);
            btnTimKiem.ForeColor = Color.White;
            btnTimKiem.Location = new Point(26, 67);
            btnTimKiem.Name = "btnTimKiem";
            btnTimKiem.ShadowDecoration.CustomizableEdges = customizableEdges2;
            btnTimKiem.Size = new Size(140, 45);
            btnTimKiem.TabIndex = 14;
            btnTimKiem.Text = "Tìm kiếm";
            btnTimKiem.Click += btnTimKiem_Click;
            // 
            // xóaToolStripMenuItem
            // 
            xóaToolStripMenuItem.Name = "xóaToolStripMenuItem";
            xóaToolStripMenuItem.Size = new Size(210, 24);
            xóaToolStripMenuItem.Text = "Xóa";
            // 
            // sửaToolStripMenuItem
            // 
            sửaToolStripMenuItem.Name = "sửaToolStripMenuItem";
            sửaToolStripMenuItem.Size = new Size(210, 24);
            sửaToolStripMenuItem.Text = "Sửa";
            // 
            // frmAdmin_QuanLyPhong
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1296, 650);
            Controls.Add(pnlRight);
            Controls.Add(pnlLeft);
            FormBorderStyle = FormBorderStyle.None;
            Name = "frmAdmin_QuanLyPhong";
            pnlLeft.ResumeLayout(false);
            pnlLeft.PerformLayout();
            pnlRight.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvPhong).EndInit();
            cmsPhong.ResumeLayout(false);
            ResumeLayout(false);
        }
        #endregion

        private Guna.UI2.WinForms.Guna2Panel pnlLeft;
        private Guna.UI2.WinForms.Guna2Panel pnlRight;
        private System.Windows.Forms.Label label2;
        private Guna.UI2.WinForms.Guna2TextBox txtTenPhong;
        private System.Windows.Forms.Label label3;
        private Guna.UI2.WinForms.Guna2TextBox txtSucChua;
        private System.Windows.Forms.Label label4;
        private Guna.UI2.WinForms.Guna2ComboBox cboLoaiPhong;
        private System.Windows.Forms.Label label5;
        private Guna.UI2.WinForms.Guna2ComboBox cboTrangThai;
        private Guna.UI2.WinForms.Guna2Button btnThem;
        private Guna.UI2.WinForms.Guna2Button btnSua;
        private Guna.UI2.WinForms.Guna2Button btnXoa;
        private Guna.UI2.WinForms.Guna2Button btnLamMoi;
        private Guna.UI2.WinForms.Guna2DataGridView dgvPhong;
        private Guna.UI2.WinForms.Guna2ContextMenuStrip cmsPhong;
        private Guna.UI2.WinForms.Guna2Button btnTimKiem;
        private Guna.UI2.WinForms.Guna2TextBox txtTimKiem;
        private ToolStripMenuItem xóaToolStripMenuItem;
        private ToolStripMenuItem sửaToolStripMenuItem;
    }
}